image:
  file: .gitpod.dockerfile
tasks:
  - init: . ${GITPOD_REPO_ROOT}/.vscode/init_tasks.sh
    command: /home/gitpod/.pg_ctl/bin/pg_start > /dev/null
  - command: . ${GITPOD_REPO_ROOT}/.vscode/uptime.sh &
vscode:
  extensions:
    - ms-python.python
    - github.vscode-pull-request-github
    - gitpod.gitpod-remote-ssh
    - ms-toolsai.jupyter
    - ms-toolsai.jupyter-keymap
    - ms-toolsai.jupyter-renderers
    - ms-python.debugpy
    - ms-python.vscode-pylance
    - ms-vscode.js-debug-nightly
    - ms-vscode.live-server
    - formulahendry.auto-close-tag
    - eventyret.bootstrap-4-cdn-snippet
    - hookyqr.beautify
    - esbenp.prettier-vscode
    - formulahendry.code-runner
    - orelhassid.npm-install
    - perkovec.emoji
    - qualc.http-server
    - redhat.vscode-yaml
    - temitope1909.dotenv-intellisense
    - tomasvergara.vscode-fontawesome-gallery
    - github.copilot
    - github.copilot-chat

