# Generated by Django 5.0.7 on 2024-09-04 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_recommendation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='education',
            field=models.CharField(max_length=200),
        ),
    ]
